[package]
name = "angine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.2.0"
assert_approx_eq = "1.1.0"
kiss3d = "0.32"
nalgebra = "0.31"

